version: '3.4'

networks:
  backend:
    
services:
  examapidb:
    container_name: examapi-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
     - SA_PASSWORD=password@12345#
     - ACCEPT_EULA=Y   
    networks: 
     - backend
    ports:
    - 8001:1433
  
  examapi:
    container_name: examapi
    image: ${DOCKER_REGISTRY-}examapi
    build:
      context: .
      dockerfile: ExamAPI/Dockerfile
    networks: 
      - backend
    ports:
     - 8002:80
    environment:
    - DB_HOST=examapi-db
    - DB_NAME=examapidb
    - DB_USER=admin
    - DB_SA_PASSWORD=password@12345#
